# version of yml standard
version: '3'

# list of services
services:

  # mysql database
  db:
    
    # build the image
    build: ./db/

    # specify the ports
    ports:
    - '9099:3306'

    # specify the volumes
    # volumes:
    # - /home/amitk/mean/db/mydb_contents:/var/lib/mysql


  # express server
  server:

    # build the image
    build: ./server/

    # specify the ports
    ports:
    - '9898:9898'


  # angular application
  app1:

     # build the image
     build: ./app1/

     # specify the ports
     ports:
     - '9090:80'

  

  

